# ==============================================================================
# Script:           ci.yml
# Purpose:          Define and configure automated Lint and tests
# ==============================================================================